name: Release

on:
  push:
    branches:
      - +([0-9])?(.{+([0-9]),x}).x
      - main
      - next
      - beta
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Cache dependencies
        id: npm-release-cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-npm-release-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-release-

      - name: Install dependencies
        if: steps.npm-release-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
